name: login_signup
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/user.png
    - assets/images/backimage.jpg

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Italic-VariableFont_opsz,wdth,wght.ttf

    - family: Merriweathernonitalic
      fonts:
        - asset: assets/fonts/Merriweather-VariableFont_opsz,wdth,wght.ttf

    - family: SpaceMonoBold
      fonts:
        - asset: assets/fonts/SpaceMonoBold.ttf

    - family: SpaceMonoRegular
      fonts:
        - asset: assets/fonts/SpaceMonoRegular.ttf